version: "3.1"

services:
  aggregator_app:
    container_name: aggregator_app
    build: ./
    working_dir: /application
    ports:
      - ${AGGREGATOR_CONTAINER_PORT}:${AGGREGATOR_HOST_PORT}
    environment:
      - AGGREGATOR_ACTIVE_PROFILE
      - AGGREGATOR_CONFIG_LOCATION
      - AGGREGATOR_HOST_PORT
      - AGGREGATOR_CONTAINER_PORT
    depends_on:
      - aggregator_db
    restart: always
    networks:
      - internal

  aggregator_db:
    image: postgres:11
    container_name: aggregator_db
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${AGGREGATOR_PG_USER}
      POSTGRES_DB: ${AGGREGATOR_PG_DB}
      POSTGRES_PASSWORD: ${AGGREGATOR_PG_PASSWORD}
      PGDATA: ${AGGREGATOR_PGDATA}
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge