version: "3.1"

services:
  jdk:
    container_name: aggregator_app
    build: ./
    working_dir: /application
    ports:
      - ${CONTAINER_PORT}:3711
    environment:
      ACTIVE_PROFILE: "development"
      CONTAINER_PORT: 3711