version: "3.1"

services:
  aggregator_app:
    container_name: aggregator_app
    build: ./
    working_dir: /application
    ports:
      - ${AGGREGATOR_CONTAINER_PORT}:${AGGREGATOR_HOST_PORT}
    environment:
      - AGGREGATOR_ACTIVE_PROFILE
      - AGGREGATOR_CONFIG_LOCATION
      - AGGREGATOR_HOST_PORT
      - AGGREGATOR_CONTAINER_PORT
    depends_on:
      - aggregator_db
    restart: always
    networks:
      - internal

  aggregator_db:
    image: postgres:11
    container_name: aggregator_db
    volumes:
      - pgdata:${AGGREGATOR_PGDATA}
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${AGGREGATOR_PG_USER}
      POSTGRES_DB: ${AGGREGATOR_PG_DB}
      POSTGRES_PASSWORD: ${AGGREGATOR_PG_PASSWORD}
      PGDATA: ${AGGREGATOR_PGDATA}
    restart: unless-stopped
    networks:
      - internal

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-myadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
  pgadmin: