version: "3.1"

services:
  jdk:
    container_name: aggregator_app
    build: ./
    working_dir: /application
    ports:
      - ${AGGREGATOR_CONTAINER_PORT}:${AGGREGATOR_HOST_PORT}
    environment:
      - AGGREGATOR_ACTIVE_PROFILE
      - AGGREGATOR_HOST_PORT
      - AGGREGATOR_CONTAINER_PORT